### ISSUE TITLE
`draft-nottingham-http-problem-04` is expired

### ISSUE THREAD

**Issue by daxim** [Codepoints/Codepoints.net#56] opened 2015-08-27 10:51 UTC
<https://github.com/Codepoints/Codepoints.net/wiki/API>

> In the case of an error the API adheres to the Problem Details for HTTP APIs draft specification.

`draft-nottingham-http-problem-04` is expired and was replaced by `draft-ietf-appsawg-http-problem`. Please check conformance and update if required.

**Comment by Boldewyn** [comment] 2015-08-27 10:58
Duplicate of #22. Pull requests welcome :)

However, my understanding of https://www.ietf.org/archive/id/draft-ietf-appsawg-http-problem-00.txt is, that this, too, expired in 2015-03. So at the moment I am a bit at a loss, whether to update at all.

**Comment by daxim** [comment] 2015-08-27 17:02
The case for updating:

* Standards are meant to enable interoperability. Assuming someone has a software implementing what's specified in HTTP problem, there's a good chance it's according to the latest one, but not one from two years ago.
* I foresee that once the draft becomes an RFC proper, your getting into compliance will be easier.

**Closed** 2015-11-23 22:05 UTC
